# Generated by Django 4.1.3 on 2022-12-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PadelClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('land', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('booked_hours', models.PositiveIntegerField(default=0)),
                ('available_hours', models.PositiveIntegerField(default=0)),
                ('utiliation_rate', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
