# Generated by Django 4.1.3 on 2023-01-07 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PadelClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=300)),
                ('price_30_min', models.CharField(blank=True, max_length=300, null=True)),
                ('price_60_min', models.CharField(blank=True, max_length=300, null=True)),
                ('price_90_min', models.CharField(blank=True, max_length=300, null=True)),
                ('price_unit', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_courts', models.IntegerField()),
                ('booked_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('available_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('utiliation_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('padel_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.padelclub')),
            ],
        ),
    ]
