# Generated by Django 4.1.3 on 2022-12-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padelclub',
            name='utiliation_rate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
