# Generated by Django 4.1.3 on 2022-12-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_alter_padelclub_utiliation_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padelclub',
            name='utiliation_rate',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
