# Generated by Django 4.1.3 on 2022-12-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_padelclub_utiliation_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='padelclub',
            name='url',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
