# Generated by Django 4.1.3 on 2022-12-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_padelclub_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padelclub',
            name='utiliation_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
