# Generated by Django 4.1.3 on 2022-12-06 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0005_alter_padelclub_utiliation_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("date", models.DateField(auto_now_add=True, verbose_name="Date")),
                (
                    "start_time",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Start Time"
                    ),
                ),
                (
                    "end_time",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="End Time"
                    ),
                ),
                (
                    "price",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Price"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Currency"
                    ),
                ),
                (
                    "is_booked",
                    models.BooleanField(default=False, verbose_name="Is Booked"),
                ),
                (
                    "is_not_available",
                    models.BooleanField(default=False, verbose_name="Is Not Available"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clubs.padelclub",
                    ),
                ),
            ],
        ),
    ]
