# Generated by Django 4.1.3 on 2022-12-06 18:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0006_slot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slot",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Date"
            ),
        ),
    ]
