# Generated by Django 4.1.3 on 2022-12-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0007_alter_slot_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="padelclub",
            name="available_hours",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="padelclub",
            name="booked_hours",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
