# Generated by Django 4.1.3 on 2022-12-11 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0008_alter_padelclub_available_hours_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Slot",
        ),
    ]
