# Generated by Django 4.1.3 on 2022-12-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0009_delete_slot"),
    ]

    operations = [
        migrations.AddField(
            model_name="padelclub",
            name="price_30_min",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="padelclub",
            name="price_60_min",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="padelclub",
            name="price_90_min",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="padelclub",
            name="price_unit",
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
