# Generated by Django 4.1.3 on 2022-12-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0010_padelclub_price_30_min_padelclub_price_60_min_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="padelclub",
            name="price_unit",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
