# Generated by Django 4.1.3 on 2022-12-19 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0011_alter_padelclub_price_unit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="padelclub",
            name="available_hours",
        ),
        migrations.RemoveField(
            model_name="padelclub",
            name="booked_hours",
        ),
        migrations.RemoveField(
            model_name="padelclub",
            name="utiliation_rate",
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no_of_courts", models.IntegerField()),
                ("booked_hours", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "available_hours",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "utiliation_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "padel_club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clubs.padelclub",
                    ),
                ),
            ],
        ),
    ]
