# Generated by Django 4.1.3 on 2022-12-26 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0012_remove_padelclub_available_hours_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="padelclub",
            old_name="land",
            new_name="city",
        ),
    ]
